<a href="https://colab.research.google.com/github/GodishalaAshwith/DeepLearning/blob/main/TensorFlowIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

##Basics

### Creating a Tensor

In [2]:
#Constants
scalar = tf.constant(5)
vector = tf.constant([1, 2, 3])
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])

#Variables
variable = tf.Variable([[1.0, 2.0], [3.0, 4.0]])

#Random Values
random_tensor = tf.random.uniform(shape=(2, 3), minval=0, maxval=10, dtype=tf.int32)

In [3]:
# Creating a 2x3 matrix tensor
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])

print("Tensor:\n", matrix)
print("Shape:", matrix.shape)
print("Data Type:", matrix.dtype)
print("Rank:", tf.rank(matrix).numpy())

Tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Shape: (2, 3)
Data Type: <dtype: 'int32'>
Rank: 2


### Manipulating Tensor Shapes

In [ ]:
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
print("Original tensor:\n", matrix)

# Reshape
reshaped = tf.reshape(matrix, shape=(3, 2))
print("\nReshaped tensor (3x2):\n", reshaped)

# Expand Dimensions
expanded = tf.expand_dims(matrix, axis=0)
print("\nExpanded tensor (added axis at the beginning):\n", expanded)

# Squeeze Dimensions (demonstrate with a tensor that has a dimension of size 1)
single_dim_tensor = tf.constant([[[1], [2], [3]]])
print("\nOriginal tensor with single dimension:\n", single_dim_tensor)
squeezed = tf.squeeze(single_dim_tensor, axis=2)
print("\nSqueezed tensor (removed axis of size 1):\n", squeezed)

# Transpose
transposed = tf.transpose(matrix, perm=[1, 0]) # Transposing a 2x3 matrix results in a 3x2 matrix
print("\nTransposed tensor:\n", transposed)

Original tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

Reshaped tensor (3x2):
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)

Expanded tensor (added axis at the beginning):
 tf.Tensor(
[[[1 2 3]
  [4 5 6]]], shape=(1, 2, 3), dtype=int32)

Original tensor with single dimension:
 tf.Tensor(
[[[1]
  [2]
  [3]]], shape=(1, 3, 1), dtype=int32)

Squeezed tensor (removed axis of size 1):
 tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)

Transposed tensor:
 tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


###Specifying Datatype

In [ ]:
import tensorflow as tf

# Creating a tensor with a specific data type
float_tensor = tf.constant([1.0, 2.0, 3.0], dtype=tf.float32)
int_tensor = tf.constant([1, 2, 3], dtype=tf.int32)
bool_tensor = tf.constant([True, False, True], dtype=tf.bool)

###Type Casting

In [ ]:
# Casting float tensor to int tensor
print(float_tensor)
casted_tensor = tf.cast(float_tensor, dtype=tf.int32)
print(casted_tensor)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


## Basic Tensor Operations

###Element Wise Operations

In [ ]:
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])

#Addition
c = tf.add(a,b) # or c = a + b
print("Addition:",c.numpy())

c = tf.subtract(a,b) # or c = a - b
print("Subtraction:",c.numpy())

c = tf.multiply(a,b) # or c = a * b
print("Multiplication:",c.numpy())

c = tf.divide(b,a) # or c = b / a
print("Division:",c.numpy())

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]


###Matrix Operations

In [ ]:
m1 = tf.constant([[1,2],[3,4]])
m2 = tf.constant([[5,6],[7,8]])

#Matrix multiplication
prod = tf.matmul(m1,m2)
print(f"Matrix Multiplication: {prod}")

#Transpose of a Matrix
t = tf.transpose(m1)
print(f"Transpose of Matrix: {t}")

Matrix Multiplication: [[19 22]
 [43 50]]
Transpose of Matrix: [[1 3]
 [2 4]]


###Slicing and Indexing

In [ ]:
# Creating a 3-D tensor
tensor = tf.constant([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])

# Slicing the first two matrices
sliced = tensor[:2]
print("Sliced Tensor:\n", sliced.numpy())

# Accessing a specific element
element = tensor[1, 1, 1]
print("Specific Element:", element.numpy())  # Output: 8

Sliced Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Specific Element: 8


###Broadcasting

In [ ]:
# Tensor A of shape (3, 1)
A = tf.constant([[1], [2], [3]])

# Tensor B of shape (1, 4)
B = tf.constant([[10, 20, 30, 40]])

# Broadcasting to shape (3, 4)
C = A + B
print("Broadcasted Tensor:\n", C.numpy())

Broadcasted Tensor:
 [[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


###Reduction Operations

In [ ]:
tensor = tf.constant([[1, 2], [3, 4]])

#Sum
sum_all = tf.reduce_sum(tensor)           # 10
sum_axis0 = tf.reduce_sum(tensor, axis=0) # [4, 6]
sum_axis1 = tf.reduce_sum(tensor, axis=1) # [3, 7]

#Mean
mean_all = tf.reduce_mean(tensor)         # 2.5
mean_axis0 = tf.reduce_mean(tensor,axis=0)# [2 3]
mean_axis1 = tf.reduce_mean(tensor,axis=1)# [1 3]

#Maximum
max_all = tf.reduce_max(tensor)           # 4
max_axis0 = tf.reduce_max(tensor,axis=0)  # [3 4]
max_axis1 = tf.reduce_max(tensor,axis=1)  # [2 4]

#Minimum
min_all = tf.reduce_min(tensor)           # 1
min_axis0 = tf.reduce_min(tensor,axis=0)  # [1 2]
min_axis1 = tf.reduce_min(tensor,axis=1)  # [1 3]

###Concatenating n Stacking

In [ ]:
tensor1 = tf.constant([[1, 2], [3, 4]])
tensor2 = tf.constant([[5, 6], [7, 8]])

# Concatenate along axis 0
concat_axis0 = tf.concat([tensor1, tensor2], axis=0)
print("Concatenated along axis 0:\n", concat_axis0.numpy())

# Concatenate along axis 1
concat_axis1 = tf.concat([tensor1, tensor2], axis=1)
print("Concatenated along axis 1:\n", concat_axis1.numpy())

# Stack tensors along a new axis
stacked = tf.stack([tensor1, tensor2], axis=0)
print("Stacked Tensor:\n", stacked.numpy())
print("Stacked Shape:", stacked.shape)  # (2, 2, 2)

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]
Stacked Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Stacked Shape: (2, 2, 2)


###Advanced Operations

One-Hot Encoding (tf.one_hot):

In [ ]:
indices = tf.constant([0, 1, 2, 1])
depth = 3
one_hot = tf.one_hot(indices, depth)
print("One-Hot Encoded Tensor:\n", one_hot.numpy())

One-Hot Encoded Tensor:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


Matrix Inversion (tf.linalg.inv):

In [ ]:
matrix = tf.constant([[1., 2.], [3., 4.]])
inverse = tf.linalg.inv(matrix)
print("Inverse of Matrix:\n", inverse.numpy())

Inverse of Matrix:
 [[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]]


Eigenvalues and Eigenvectors (tf.linalg.eig):

In [ ]:
matrix = tf.constant([[1., 2.], [3., 4.]])
eigenvalues, eigenvectors = tf.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues.numpy())
print("Eigenvectors:\n", eigenvectors.numpy())

Eigenvalues: [-0.37228122+0.j  5.372281  +0.j]
Eigenvectors:
 [[-0.8245648 +0.j -0.41597357+0.j]
 [ 0.56576747+0.j -0.90937674+0.j]]


#Core Tensorflow Concepts

##Variables and Constants


In [ ]:
import tensorflow as tf

# Creating a constant tensor
const_tensor = tf.constant([1, 2, 3], dtype=tf.int32)
print("Constant Tensor:", const_tensor)
# Creating a variable tensor
var_tensor = tf.Variable([1.0, 2.0, 3.0], dtype=tf.float32)
print("Variable Tensor:", var_tensor)

Constant Tensor: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Variable Tensor: <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>


In [ ]:
import tensorflow as tf

# Define Constants for input data
X = tf.constant([[1.0], [2.0], [3.0], [4.0]], dtype=tf.float32)  # Input features
Y = tf.constant([[2.0], [4.0], [6.0], [8.0]], dtype=tf.float32)  # Target values

# Define Variables for model parameters (weights and bias)
W = tf.Variable([[0.0]], dtype=tf.float32, name='weight')
b = tf.Variable([0.0], dtype=tf.float32, name='bias')

# Define the linear model
def linear_model(X):
    return tf.matmul(X, W) + b

# Define the loss function (Mean Squared Error)
def loss_fn(y_pred, y_true):
    return tf.reduce_mean(tf.square(y_pred - y_true))

# Define the optimizer
optimizer = tf.optimizers.SGD(learning_rate=0.01)

# Training loop
for epoch in range(1000):
    with tf.GradientTape() as tape:
        y_pred = linear_model(X)
        loss = loss_fn(y_pred, Y)

    # Compute gradients
    gradients = tape.gradient(loss, [W, b])

    # Update variables
    optimizer.apply_gradients(zip(gradients, [W, b]))

    if epoch % 100 == 0:
        print(f"Epoch {epoch}: Loss = {loss.numpy()}, W = {W.numpy()}, b = {b.numpy()}")

# Final model parameters
print("Trained Weights:", W.numpy())
print("Trained Bias:", b.numpy())

Epoch 0: Loss = 30.0, W = [[0.29999998]], b = [0.09999999]
Epoch 100: Loss = 0.03408462926745415, W = [[1.8468075]], b = [0.45040485]
Epoch 200: Loss = 0.01871202513575554, W = [[1.8864939]], b = [0.33372158]
Epoch 300: Loss = 0.010272667743265629, W = [[1.9158992]], b = [0.24726659]
Epoch 400: Loss = 0.005639577750116587, W = [[1.9376867]], b = [0.18320896]
Epoch 500: Loss = 0.0030960547737777233, W = [[1.9538298]], b = [0.13574634]
Epoch 600: Loss = 0.001699708285741508, W = [[1.9657906]], b = [0.10057957]
Epoch 700: Loss = 0.0009331251494586468, W = [[1.974653]], b = [0.0745233]
Epoch 800: Loss = 0.0005122720031067729, W = [[1.9812194]], b = [0.05521719]
Epoch 900: Loss = 0.00028123249649070203, W = [[1.9860847]], b = [0.04091255]
Trained Weights: [[1.9896587]]
Trained Bias: [0.03040474]


##Operations and Sessions

In [ ]:
import tensorflow as tf

# Define two constant tensors
a = tf.constant(2.0)
b = tf.constant(3.0)

# Define an addition operation
c = tf.add(a, b)
print("Operation:", c)

Operation: tf.Tensor(5.0, shape=(), dtype=float32)


In [ ]:
# In TensorFlow 2.x, eager execution is enabled by default, so no session is needed.
# The operation `c = tf.add(a, b)` is executed immediately.
# You can directly access the value of the tensor using .numpy()
print("Result:", c.numpy())

Result: 5.0


In [ ]:
import tensorflow as tf

# Define Variables
W = tf.Variable([0.3], dtype=tf.float32, name='weight')
b = tf.Variable([-0.3], dtype=tf.float32, name='bias')

# Define Operations
X = tf.placeholder(tf.float32, name='input')
linear_model = W * X + b

# Define a loss function (Mean Squared Error)
Y = tf.placeholder(tf.float32, name='target')
loss = tf.reduce_mean(tf.square(linear_model - Y))

# Initialize variables
init = tf.global_variables_initializer()

# Define an optimizer
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(loss)

# Training data
train_X = [1, 2, 3, 4]
train_Y = [0, -1, -2, -3]

# Start a session
with tf.Session() as sess:
    # Initialize variables
    sess.run(init)

    # Training loop
    for epoch in range(1000):
        for x, y in zip(train_X, train_Y):
            sess.run(train, feed_dict={X: x, Y: y})

    # After training
    final_W, final_b, final_loss = sess.run([W, b, loss], feed_dict={X: train_X, Y: train_Y})
    print(f"Trained Weight: {final_W}")
    print(f"Trained Bias: {final_b}")
    print(f"Final Loss: {final_loss}")

Epoch 0: Loss = 5.914999961853027, W = [0.17000002], b = [-0.33900002]
Epoch 100: Loss = 0.22356565296649933, W = [-0.60766166], b = [-0.1535226]
Epoch 200: Loss = 0.12273482233285904, W = [-0.7093019], b = [0.14531225]
Epoch 300: Loss = 0.06737996637821198, W = [-0.7846109], b = [0.3667299]
Epoch 400: Loss = 0.03699078783392906, W = [-0.84041023], b = [0.5307866]
Epoch 500: Loss = 0.020307529717683792, W = [-0.88175386], b = [0.6523421]
Epoch 600: Loss = 0.011148570105433464, W = [-0.9123871], b = [0.7424075]
Epoch 700: Loss = 0.00612042099237442, W = [-0.9350844], b = [0.80914026]
Epoch 800: Loss = 0.003360041882842779, W = [-0.9519016], b = [0.8585849]
Epoch 900: Loss = 0.0018446184694766998, W = [-0.96436214], b = [0.8952204]
Trained Weight: [-0.9735152]
Trained Bias: [0.92213166]
Final Loss: 0.0010126777924597263


##Placeholders

In [ ]:
from tensorflow.keras.layers import Input
input_layer = Input(shape=(784,), name='input_layer')

In [ ]:
import tensorflow as tf

# Create a dataset
dataset = tf.data.Dataset.from_tensor_slices((train_X, train_Y))
dataset = dataset.batch(32)

# Iterate over the dataset
for batch_X, batch_Y in dataset:
    # Perform training step
    pass

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

# Define a simple model
model = Sequential([
    Dense(10, activation='relu', input_shape=(784,)),
    Dense(1)
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Generate dummy data
X = np.random.rand(100, 784)
Y = np.random.rand(100, 1)

# Train the model
model.fit(X, Y, epochs=5)

Epoch 1/5


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.1751
Epoch 2/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1862 
Epoch 3/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1160 
Epoch 4/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1087 
Epoch 5/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0878 


In [ ]:
import tensorflow as tf

# Define placeholders
X = tf.placeholder(tf.float32, shape=[None, 784])
Y = tf.placeholder(tf.float32, shape=[None, 10])

# Define a simple neural network
W = tf.Variable(tf.random_normal([784, 10]))
b = tf.Variable(tf.random_normal([10]))
logits = tf.matmul(X, W) + b

# Define loss and optimizer
loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=Y, logits=logits))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.5).minimize(loss)

# Start a session
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # Training loop
    for epoch in range(1000):
        batch_X, batch_Y = get_next_batch()  # Assume this function fetches a batch
        sess.run(optimizer, feed_dict={X: batch_X, Y: batch_Y})

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

# Define a simple neural network using Keras
model = Sequential([
    Dense(10, activation='relu', input_shape=(784,)),
    Dense(10, activation='softmax')
])

# Compile the model
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.5),
              loss='categorical_crossentropy')

# Generate dummy data
X_train = np.random.rand(1000, 784)
Y_train = tf.keras.utils.to_categorical(np.random.randint(10, size=(1000, 1)), num_classes=10)

# Train the model
model.fit(X_train, Y_train, epochs=1000, batch_size=32)

Epoch 1/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 2.3862
Epoch 2/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.2920
Epoch 3/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.2993
Epoch 4/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.3025
Epoch 5/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.3007
Epoch 6/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.3019
Epoch 7/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.2999  
Epoch 8/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.2965 
Epoch 9/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.3007
Epoch 10/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.3076 
Epoch 11/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.3029 
Epoch 12/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.3029 
Epoch 13/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.3024 
Epoch 14/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.2999
Epoch 15/1000
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/st